config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks, only: %i(new create)
  root "feedbacks#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feedback.rb
class Feedback
  include ActiveModel::Validations

  ATTRIBUTES = %i(name email body).freeze
  EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  attr_reader(*ATTRIBUTES)

  validates(*ATTRIBUTES, presence: true)
  validates :email, format: { with: EMAIL_FORMAT }

  def initialize(opts = {})
    @name  = opts[:name]
    @email = opts[:email]
    @body  = opts[:body]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def new
    @feedback = Feedback.new
  end

  def create
    @feedback = Feedback.new(feedback_params)

    if @feedback.valid?
      FeedbackMailer.admin_email(@feedback).deliver
      redirect_to root_path, notice: "Mail sent successfuly."
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(*Feedback::ATTRIBUTES)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/feedbacks/new.html.erb
<p>
  <%= flash[:notice] %>
</p>

<%= form_for :feedback, url: feedbacks_path do |f| %>
  <% if @feedback.errors.to_a.any? %>
    <% @feedback.errors.to_a.each do |error_message| %>
      <%= error_message %>
      <br />
    <% end %>
  <% end %>

  Name: <%= f.text_field :name %><br />
  Email: <%= f.text_field :email %><br />
  Message : <%= f.text_area :body %><br />
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevelopmentFlow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>